### ISSUE TITLE
7777 Failure to Connect 

### ISSUE THREAD

**Issue by djordanw** [whilenull/7777-support#43]
Hey team, 

Since the most recent container push it seems we're unable to connect to any database instances through 7777. When attempting to connect with the `--verbose` flag, we get the following output:

```
Retrieving the availability zone and subnet of your instance.
Retrieving the container security group.
Retrieving the computer's IP address.
Authorizing x.x.x.x on the security group.
Starting the Fargate container.
The IP address of the container is x.x.x.x.
Starting the SSH tunnel to x.x.x.x:22.
```

Following this, the command just seems to die without connecting to the database. 

Looking at the macos activity log, it looks like there's a lot of start/stop activity with `mDNSResponder`. There does not appear to be any crash report generated.

**Comment by dhrrgn** [comment]
We are having this issue as well.  I have found that I can connect if I specify the `--forever` flag. This is not ideal though.

**Comment by mnapoli** [comment]
Thanks for the report!

The latest version includes multiple upgrades in the binary. In the Fargate container, the only change is that Alpine was upgraded from 3.12 to 3.18 (latest tag: https://hub.docker.com/_/alpine/tags)

I'm trying to understand whether the issue comes from the bastion container upgrade, or another dependency upgrade in the binary 🤔

I strongly suspect it's the container update, because when testing locally (with the updated binary) I had no issue. And now that the release is published, the binary is using the updated server image and it's now failing just like you guys…

**Comment by mnapoli** [comment]
Here is the script the Fargate container (Alpine) is running:

```sh
#!/bin/sh

echo ${AUTHORIZED_KEYS} > ~/.ssh/authorized_keys

/usr/sbin/sshd &

sleep ${TERMINATE_AFTER_SECONDS:-7200}
```

I suspect that the `sleep` line is the issue. If we use `--forever`, then `TERMINATE_AFTER_SECONDS`'s value is `infinity`.

**Comment by shadowhand** [comment]
@mnapoli is it possible that the `TERMINATE_AFTER_SECONDS` is somehow not being populated correctly, resulting in the value being (effectively) `0` so it becomes `sleep -7200`.

**Comment by mnapoli** [comment]
Right! I had a look in the Fargate console, I can see the variable correctly populated though 🤔

<img width="422" alt="image" src="https://github.com/whilenull/7777-support/assets/720328/2dccfed8-5836-4bc5-a513-60c3d1c2c54c">

**Comment by mnapoli** [comment]
It is working for me with `--forever`

I just pushed a new version of the Docker image with logs:

```sh
#!/bin/sh

echo "Starting"

echo ${AUTHORIZED_KEYS} > ~/.ssh/authorized_keys

echo "Starting the SSH daemon"

/usr/sbin/sshd &

echo "SSH is starting, the container will terminate in ${TERMINATE_AFTER_SECONDS:-7200} seconds"

sleep ${TERMINATE_AFTER_SECONDS:-7200}

echo "Timeout: terminating after ${TERMINATE_AFTER_SECONDS:-7200} seconds"
```

Here is what I'm getting in the logs:

```
5/24/2023, 4:55:00 PM GMT+2 | Timeout: terminating after 7200 seconds
5/24/2023, 4:55:00 PM GMT+2 | SSH is starting, the container will terminate in 7200 seconds
5/24/2023, 4:55:00 PM GMT+2 | Starting the SSH daemon
5/24/2023, 4:55:00 PM GMT+2 | Starting
```

That makes no sense 😅 

Something is definitely up with the `sleep`

**Comment by mnapoli** [comment]
Fixed! I guess an SSH upgrade changed the options for the daemon? Anyway, `/usr/sbin/sshd -e -D &` made much more sense and it's now running fine.

You shouldn't need to update the CLI (I'll push a new version with more logs anyway, will be useful for the future), the new version of the container should be picked up immediately.

Let me know if you have any issue!

**Comment by robzawarski** [comment]
Well this is going from bad to worse. I have been having the same issue reported above -- getting to starting SSH server and then nothing. Decided to uninstall and run again. The stack was successfully deleted, but now I get this when I run 7777.exe (I am on windows):

(node:8592) UnhandledPromiseRejectionWarning: ReferenceError: rollbar is not defined
    at C:\snapshot\7777\bin\run:56:13
(Use `7777 --trace-warnings ...` to show where the warning was created)
(node:8592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:8592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

Help!

**Comment by shadowhand** [comment]
Confirmed that 7777 SSH tunnel is not immediately exiting, the issue is solved (at least for OSX).

**Comment by robzawarski** [comment]
I was not able to reinstall using Windows client because of error reported above. I was able to open WSL and install using the linux client. However, following install, the same error that started all this, dying after "Starting the SSH tunnel" still occurs.

From my linux client:

Checking if 7777 is set up in the AWS account.
7777 is already set up, moving on.
Retrieving the container security group.
Retrieving the computer's IP address.
Authorizing 64.121.173.29 on the security group.
Starting the Fargate container.
The IP address of the container is 18.208.187.154.
Starting the SSH tunnel to 18.208.187.154:22.

And the dies. The task keeps running on ECS. Here is an output from the log:

  | 2023-05-24T15:33:13.003-04:00 | Starting the SSH daemon
  | 2023-05-24T15:33:13.003-04:00 | SSH is starting, the container will terminate in 7200 seconds
  | 2023-05-24T15:33:13.077-04:00 | Server listening on 0.0.0.0 port 22.
  | 2023-05-24T15:33:13.077-04:00 | Server listening on :: port 22.
  | 2023-05-24T15:33:16.227-04:00 | Unable to negotiate with 64.121.173.29 port 56126: no matching host key type found. Their offer: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa [preauth]
  | 2023-05-24T15:33:16.228-04:00 | Timeout: terminating after 7200 seconds

Help!

**Comment by mnapoli** [comment]
@robzawarski could you confirm the `7777 --version` in both cases? (Windows and WSL)

It should be `1.1.12`. Both of these errors sound like issues with older versions, so I'd love to be sure first.

**Comment by robzawarski** [comment]
Ok. I was using an older version on Windows. Using the 1.1.12 version, on Windows, I was able to successfully perform a '7777.exe uninstall' and then 7777.exe and it successfully connected. 

Thanks!!!!!!!!

**Comment by mnapoli** [comment]
Great, thanks for the update!
